import type { Metadata } from "next"
import { Toaster } from "sonner"

import Container from "@/components/Container"

import Providers from "./providers"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='zh-Hant-TW'>
      <body>
        <Toaster
          richColors
          toastOptions={{
            classNames: {
              toast: "backdrop-blur-none"
            }
          }}
        />
        <Providers>
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  )
}
